name: Daily Startup Briefing

on:
  schedule:
    # 매일 07:30 KST == 매일 22:30 UTC (전날)
    - cron: "30 22 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator
        run: |
          python scripts/fetch_and_build.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/*.md
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore: daily briefing $(date -u +'%Y-%m-%d')"
            git push
          fi
